In [14]:
import pandas as pd
import numpy as np

In [15]:
data_path = "/Users/kevinmbp/Desktop/2D_spec_dict/data/short_peptide/deconv/VEA3+_annotated.txt"
data = pd.read_csv(data_path, sep = '\t')

In [18]:
data = data[data['Ranking'] != -1]
data = data.sort_values('Ranking')
contain = data[data['Ranking'] == 48]
contain

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B
94,187.072039,596.845575,16964459.0,15695268.0,410.93859,48,1,539,186.0648,187.0720,2,10020,1191.6766,1192.6839
95,596.845575,187.072039,16964459.0,15695268.0,410.93859,48,2,9974,1191.6766,1192.6839,1,531,186.0648,187.0720

In [20]:
data_path = "/Users/kevinmbp/Desktop/2D_spec_dict/data/short_peptide/deconv/VEA3+_annotated.txt"
data = pd.read_csv(data_path, sep = '\t')
non_contain = data[data['Ranking'] == 48]
non_contain

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B
94,187.072039,596.845575,16964459.0,15695268.0,410.93859,48,1,539,186.0648,187.0720,2,10020,1191.6766,596.8456
95,596.845575,187.072039,16964459.0,15695268.0,410.93859,48,2,9974,1191.6766,596.8456,1,531,186.0648,187.0720

In [21]:
data_path = "/Users/kevinmbp/Desktop/2D_spec_dict/data/short_peptide/deconv/VEA3+_annotated.txt"
data = pd.read_csv(data_path, sep = '\t')
non_contain = data[data['Ranking'] == 7]
non_contain

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B
12,1008.563901,371.193813,18755287.0,18322403.0,908.68617,7,1,15832,1007.5566,1008.5639,1,2769,370.1865,371.1938
13,371.193813,1008.563901,18755287.0,18322403.0,908.68617,7,1,2798,370.1865,371.1938,1,15897,1007.5566,1008.5639

In [22]:
non_contain = data[data['Ranking'] == 9]
non_contain

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B
16,596.845575,415.183883,140359140.0,117995480.0,856.04609,9,2,10033,1191.6766,596.8456,1,4241,414.1766,415.1839
17,415.183883,596.845575,140359140.0,117995480.0,856.04609,9,1,4234,414.1766,415.1839,2,9886,1191.6766,596.8456