In [14]:
import pandas as pd
import numpy as np

In [15]:
data_path = "/Users/kevinmbp/Desktop/2D_spec_dict/data/short_peptide/deconv/VEA3+_annotated.txt"
data = pd.read_csv(data_path, sep = '\t')

In [18]:
data = data[data['Ranking'] != -1]
data = data.sort_values('Ranking')
contain = data[data['Ranking'] == 48]
contain

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B
94,187.072039,596.845575,16964459.0,15695268.0,410.93859,48,1,539,186.0648,187.0720,2,10020,1191.6766,1192.6839
95,596.845575,187.072039,16964459.0,15695268.0,410.93859,48,2,9974,1191.6766,1192.6839,1,531,186.0648,187.0720

In [20]:
data_path = "/Users/kevinmbp/Desktop/2D_spec_dict/data/short_peptide/deconv/VEA3+_annotated.txt"
data = pd.read_csv(data_path, sep = '\t')
non_contain = data[data['Ranking'] == 48]
non_contain

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B
94,187.072039,596.845575,16964459.0,15695268.0,410.93859,48,1,539,186.0648,187.0720,2,10020,1191.6766,596.8456
95,596.845575,187.072039,16964459.0,15695268.0,410.93859,48,2,9974,1191.6766,596.8456,1,531,186.0648,187.0720

In [21]:
data_path = "/Users/kevinmbp/Desktop/2D_spec_dict/data/short_peptide/deconv/VEA3+_annotated.txt"
data = pd.read_csv(data_path, sep = '\t')
non_contain = data[data['Ranking'] == 7]
non_contain

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B
12,1008.563901,371.193813,18755287.0,18322403.0,908.68617,7,1,15832,1007.5566,1008.5639,1,2769,370.1865,371.1938
13,371.193813,1008.563901,18755287.0,18322403.0,908.68617,7,1,2798,370.1865,371.1938,1,15897,1007.5566,1008.5639

In [22]:
non_contain = data[data['Ranking'] == 9]
non_contain

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B
16,596.845575,415.183883,140359140.0,117995480.0,856.04609,9,2,10033,1191.6766,596.8456,1,4241,414.1766,415.1839
17,415.183883,596.845575,140359140.0,117995480.0,856.04609,9,1,4234,414.1766,415.1839,2,9886,1191.6766,596.8456

In [26]:
df_msms = pd.read_csv(
    "/Users/kevinmbp/Desktop/2D_spec_dict/data/virtual_MSMS/VEADIAGHGQEVLIR-mz536-z3_Intensity_Sum",
    sep=r"\s+",
    header=None,
    names=["intensity", "mz", "error", "annotation"],
    engine="python",
    usecols=[0, 1, 2, 3]
)

In [28]:
df_msms.head()

     intensity          mz        error annotation
0   968.253174  156.102426 -1000.000000         No
1  8633.249023  175.119605    -0.000653         y1
2  6728.792969  183.113388    -0.000584  b2-H2O-CO
3   973.557800  187.072039    -0.000706   internal
4  1063.230103  195.088350    -0.000698   internal

In [30]:
data[data['Ranking'] == 3]

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B
4,300.156407,654.359227,355823770.0,262187790.0,1054.3404,3,1,2588,299.1491,300.1564,2,11580,1305.7356,653.8751
5,654.359227,300.156407,355823770.0,262187790.0,1054.3404,3,2,11590,1305.7356,653.8751,1,2557,299.1491,300.1564

In [31]:
data[data['Ranking'] == 6]

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B
10,300.156407,654.860832,194805700.0,152553350.0,913.39267,6,1,2452,299.1491,300.1564,2,11580,1305.7356,653.8751
11,654.860832,300.156407,194805700.0,152553350.0,913.39267,6,2,11432,1305.7356,653.8751,1,2589,299.1491,300.1564

In [32]:
data[data['Ranking'] ==44]

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B
86,655.362039,300.156407,38377238.0,30956076.0,419.96469,44,2,11465,1305.7356,653.8751,1,2503,299.1491,300.1564
87,300.156407,655.362039,38377238.0,30956076.0,419.96469,44,1,2457,299.1491,300.1564,2,11471,1305.7356,653.8751

In [42]:
df_msms[(df_msms['mz'] <= (655.362039 + 2)) & (df_msms['mz'] >= (655.362039 - 2))]

         intensity          mz        error annotation
106    1106.595581  653.875096 -1000.000000         No
107  108949.343750  654.359227    -0.002276        y12
108   48794.230469  654.860832    -0.002204        y12
109    9481.617188  655.362039 -1000.000000         No

In [39]:
sum(df_msms['intensity'] < 655.362039 + 1)

0

In [ ]:
data_path = "/Users/kevinmbp/Desktop/2D_spec_dict/data/short_peptide/deconv/VEA3+intensity_annotated.txt"
df = pd.read_csv(data_path, sep="\t", engine="python")
df[(df['Ranking'] == 3)][['m/z A', 'm/z B', 'deconvoluted_mz_A', 'intensity A']]

        m/z A       m/z B  deconvoluted_mz_A    intensity A
4  300.156407  654.359227           299.1531   33528.605469
5  654.359227  300.156407           654.3592  108949.343750

In [63]:
df[(df['envelope_id_A'] == 2588) | (df['envelope_id_B'] == 2588)]

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,intensity A,intensity B,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,isotope_similarity_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B,isotope_similarity_B
4,300.156407,654.359227,3.558238e+08,2.621878e+08,1054.340400,3,33528.605469,108949.343750,1,2588,298.1458,299.1531,0.9985,2,11580,1306.7039,654.3592,0.9643
12152,428.215597,300.156407,8.304274e+05,5.946674e+04,3.454600,6077,1113.214722,33528.605469,1,4512,428.1922,429.1995,1.0000,1,2588,298.1458,299.1531,0.9985
12594,536.242818,301.159861,0.000000e+00,0.000000e+00,0.000000,6298,777.040710,2384.458984,1,9115,535.2355,536.2428,NaN,1,2588,298.1458,299.1531,0.9985
19420,301.159861,399.225909,-2.196001e+05,-2.366732e+05,-60.965164,9711,2384.458984,941.856201,1,2588,298.1458,299.1531,0.9985,1,3529,397.2252,398.2324,0.8567

In [66]:
df[(df['Ranking'] == 12)]

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,intensity A,intensity B,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,isotope_similarity_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B,isotope_similarity_B
22,528.268562,540.303260,82621553.0,72492860.0,769.61895,12,5624.222656,81014.875000,1,8295,529.2806,530.2879,0.9924,2,9173,1077.5886,539.8016,0.9993
23,540.303260,528.268562,82621553.0,72492860.0,769.61895,12,81014.875000,5624.222656,2,9242,1077.5886,539.8016,0.9993,1,8141,529.2806,530.2879,0.9924

In [67]:
df[(df['envelope_id_A'] == 8295)]

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,intensity A,intensity B,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,isotope_similarity_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B,isotope_similarity_B
22,528.268562,540.303260,82621553.00,72492860.00,769.618950,12,5624.222656,81014.875000,1,8295,529.2806,530.2879,0.9924,2,9173,1077.5886,539.8016,0.9993
6609,529.270973,371.193813,336664.71,286388.87,56.858449,3305,1108.264771,2637.109131,1,8295,529.2806,530.2879,0.9924,1,2799,370.1865,371.1938,NaN
12989,530.287900,536.242818,0.00,0.00,0.000000,6495,12948.754883,777.040710,1,8295,529.2806,530.2879,0.9924,1,9149,535.2355,536.2428,NaN
14361,532.294456,814.482029,209076.66,-183141.15,-10.378494,7181,750.020203,21098.802734,1,8295,529.2806,530.2879,0.9924,1,15192,812.4714,813.4787,0.9998
20929,531.286332,501.360683,-359860.19,-486401.05,-78.552677,10465,2229.270752,1174.901367,1,8295,529.2806,530.2879,0.9924,1,6967,498.3468,499.3541,0.9998

In [68]:
df[(df['Ranking'] == 19)]

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,intensity A,intensity B,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,isotope_similarity_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B,isotope_similarity_B
36,951.541865,428.215597,7178952.0,7105385.0,662.22646,19,4298.900879,1113.214722,1,15497,949.5312,950.5385,1.0,1,4657,428.1922,429.1995,1.0
37,428.215597,951.541865,7178952.0,7105385.0,662.22646,19,1113.214722,4298.900879,1,4523,428.1922,429.1995,1.0,1,15538,949.5312,950.5385,1.0

In [69]:
df[(df['envelope_id_A'] == 15497)]

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,intensity A,intensity B,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,isotope_similarity_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B,isotope_similarity_B
36,951.541865,428.215597,7178952.0,7105385.0,662.226460,19,4298.900879,1113.214722,1,15497,949.5312,950.5385,1.0,1,4657,428.1922,429.1995,1.0000
4397,952.544553,746.395337,1167766.8,1064822.7,84.295705,2199,1306.884277,4973.362305,1,15497,949.5312,950.5385,1.0,2,14171,1487.7710,744.8928,0.9976

In [74]:
data_path = "/Users/kevinmbp/Desktop/2D_spec_dict/data/long_peptide/deconv/HAD4+intensity_annotated.txt"
df = pd.read_csv(data_path, sep="\t", engine="python")
df[(df['Ranking'] == 1)][['m/z A', 'm/z B', 'deconvoluted_mz_A', 'intensity A', 'deconvoluted_mz_B', 'intensity B']]

,m/z A,m/z B,deconvoluted_mz_A,intensity A,deconvoluted_mz_B,intensity B
0,476.274275,1097.865943,476.2743,98392.0625,1097.5315,128894.265625

In [85]:
df[(df['Ranking'] == 244)]

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,intensity A,intensity B,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,isotope_similarity_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B,isotope_similarity_B
243,209.104503,1186.587663,8454.6122,8432.5908,228.87577,244,3655.753662,1083.544067,1,25,208.0972,209.1045,NaN,3,575,3555.7421,1186.2546,0.9965

In [86]:
df[(df['envelope_id_B'] == 575)]

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,intensity A,intensity B,charge_A,envelope_id_A,monoisotopic_mass_A,deconvoluted_mz_A,isotope_similarity_A,charge_B,envelope_id_B,monoisotopic_mass_B,deconvoluted_mz_B,isotope_similarity_B
243,209.104503,1186.587663,8454.6122,8432.5908,228.87577,244,3655.753662,1083.544067,1,25,208.0972,209.1045,NaN,3,575,3555.7421,1186.2546,0.9965
1074,760.335250,1186.923542,9364.2978,9206.0100,151.48949,1075,7126.022949,1370.823364,1,526,759.3280,760.3352,NaN,3,575,3555.7421,1186.2546,0.9965

In [113]:
data_path = "/Users/kevinmbp/Desktop/2D_spec_dict/data/long_peptide/deconv/HAD4_ffc_annotated.txt"
df = pd.read_csv(data_path, sep="\t", engine="python")

In [115]:
df[(df['Ranking'] == 443)]

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,intensity A,intensity B,line_id,i,...,charge_A,charge_B,envelope_id_A,envelope_id_B,deconvoluted_mz_A,deconvoluted_mz_B,monoisotopic_mass_A,monoisotopic_mass_B,isotope_similarity_A,isotope_similarity_B
18,348.178404,1139.896002,313432.6,208262.55,183.14002,443,130760.367188,71698.328125,7,1,...,1,3,4,52,346.1713,3417.6723,345.164,3416.665,0.9999,0.9913

In [116]:
df[(df['Ranking'] == 9)]

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,intensity A,intensity B,line_id,i,...,charge_A,charge_B,envelope_id_A,envelope_id_B,deconvoluted_mz_A,deconvoluted_mz_B,monoisotopic_mass_A,monoisotopic_mass_B,isotope_similarity_A,isotope_similarity_B
190,348.178404,1140.230185,1775340.5,1380546.9,667.229,9,130760.367188,232353.625,5,1,...,1,3,4,52,346.1713,3417.6723,345.164,3416.665,0.9999,0.9913

In [117]:
df[(df['envelope_id_B'] == 52)][['m/z B', 'intensity B', 'charge_B', 'deconvoluted_mz_B', 'Ranking']]

           m/z B    intensity B  charge_B  deconvoluted_mz_B  Ranking
18   1139.896002   71698.328125         3          3417.6723      443
147  1140.564372  250522.953125         3          3417.6723        7
150  1139.896002   71698.328125         3          3417.6723     1265
154  1140.230185  232353.625000         3          3417.6723      521
173  1140.898630  156847.343750         3          3417.6723       13
174  1140.230185  232353.625000         3          3417.6723      321
176  1140.564372  250522.953125         3          3417.6723      205
190  1140.230185  232353.625000         3          3417.6723        9
194  1139.896002   71698.328125         3          3417.6723      991

In [119]:
df[(df['envelope_id_A'] == 4)][['m/z A', 'intensity A', 'charge_A', 'deconvoluted_mz_A', 'Ranking']]

          m/z A    intensity A  charge_A  deconvoluted_mz_A  Ranking
18   348.178404  130760.367188         1           346.1713      443
147  348.178404  130760.367188         1           346.1713        7
150  350.183780    1713.923096         1           346.1713     1265
154  349.181847   15978.585938         1           346.1713      521
173  348.178404  130760.367188         1           346.1713       13
174  350.183780    1713.923096         1           346.1713      321
176  349.181847   15978.585938         1           346.1713      205
190  348.178404  130760.367188         1           346.1713        9
194  349.181847   15978.585938         1           346.1713      991

In [121]:
df[(df['Ranking'] == 37)]

,m/z A,m/z B,Covariance,Partial Cov.,Score,Ranking,intensity A,intensity B,line_id,i,...,charge_A,charge_B,envelope_id_A,envelope_id_B,deconvoluted_mz_A,deconvoluted_mz_B,monoisotopic_mass_A,monoisotopic_mass_B,isotope_similarity_A,isotope_similarity_B
153,477.277555,1097.531602,328248.56,300365.71,494.73448,37,18388.570313,125307.726563,3,1,...,1,3,6,51,477.278,3289.5763,476.2707,3288.569,NaN,0.9918

In [122]:
df[(df['envelope_id_B'] == 51)][['m/z B', 'intensity B', 'charge_B', 'deconvoluted_mz_B', 'Ranking']]

           m/z B    intensity B  charge_B  deconvoluted_mz_B  Ranking
20   1097.197400   43545.941406         3          3289.5763      101
148  1097.197400   43545.941406         3          3289.5763      219
151  1097.865943  128894.265625         3          3289.5763        1
153  1097.531602  125307.726563         3          3289.5763       37
158  1097.865943  128894.265625         3          3289.5763     1059
170  1098.199865   74608.390625         3          3289.5763        2
172  1097.531602  125307.726563         3          3289.5763      431
178  1097.865943  128894.265625         3          3289.5763       90
191  1097.531602  125307.726563         3          3289.5763        3
192  1097.197400   43545.941406         3          3289.5763       71